name: Build a microservice helm chart
branding:
  icon: 'package'
  color: 'black'
inputs:
  version:
    description: 'The helm chart version'
    required: true
  artifact_name:
    description: 'The base name of the helm chart, defaults to repository name.'
    required: false
    default: '${{ github.event.repository.name }}'
  helm_repo_url:
    description: 'The helm repository url'
    required: true
  helm_repo_username:
    description: 'The helm repository username'
    required: true
  helm_repo_password:
    description: 'The helm repository password'
    required: true
outputs:
  uploaded_file:
    description: 'The url of the uploaded artifact'
runs:
  using: docker
  image: Dockerfile
  env:
    VERSION: ${{ inputs.version }}
    ARTIFACT_NAME: ${{ inputs.artifact_name }}
    REPO_URL: ${{ inputs.helm_repo_url }}
    REPO_USER: ${{ inputs.helm_repo_username }}
    REPO_PASS: ${{ inputs.helm_repo_password }}